# Generated by Django 5.2.16 on 2026-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "niche",
                    models.CharField(
                        blank=True,
                        help_text="e.g. horror, history, sci-fi, bedtime",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "style_prompt",
                    models.TextField(
                        blank=True,
                        help_text="System/style prompt used when generating scripts and image prompts.",
                    ),
                ),
                (
                    "elevenlabs_voice_id",
                    models.CharField(
                        blank=True,
                        help_text="Default ElevenLabs narrator voice for this profile.",
                        max_length=100,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
