# Generated by Django 5.2.16 on 2026-07-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="narrator_voice",
            field=models.CharField(
                blank=True,
                help_text="Narrator voice for the active TTS provider (e.g. an ElevenLabs voice ID, or a Kokoro voice like 'af_heart'). Blank uses the default.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="elevenlabs_voice_id",
            field=models.CharField(
                blank=True,
                help_text="(Deprecated) legacy ElevenLabs voice field.",
                max_length=100,
            ),
        ),
    ]
