# Generated by Django 5.2.16 on 2026-07-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "niche",
                    models.CharField(
                        blank=True,
                        help_text="e.g. horror, history, sci-fi, bedtime",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "style_prompt",
                    models.TextField(
                        blank=True,
                        help_text="System/style prompt used when generating scripts and image prompts.",
                    ),
                ),
                (
                    "narrator_voice",
                    models.CharField(
                        blank=True,
                        help_text="Narrator voice for the active TTS provider (e.g. an ElevenLabs voice ID, or a Kokoro voice like 'af_heart'). Blank uses the default.",
                        max_length=100,
                    ),
                ),
                (
                    "elevenlabs_voice_id",
                    models.CharField(
                        blank=True,
                        help_text="(Deprecated) legacy ElevenLabs voice field.",
                        max_length=100,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_templates",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("account", "name")},
            },
        ),
    ]
