# Generated by Django 5.2.16 on 2026-07-30 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_number", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=300)),
                (
                    "body",
                    models.TextField(help_text="This part's slice of the full script."),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("narration_audio_path", models.CharField(blank=True, max_length=500)),
                ("audio_start_seconds", models.FloatField(blank=True, null=True)),
                ("audio_end_seconds", models.FloatField(blank=True, null=True)),
                ("video_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="ChapterImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("image_prompt", models.TextField()),
                ("image_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="videos.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GenerationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("script", "Generate script"),
                            ("split", "Split into parts"),
                            ("images", "Generate images"),
                            ("narration", "Generate narration"),
                            ("render_part", "Render part video"),
                            ("merge", "Merge narration"),
                            ("render", "Render video"),
                            ("subtitles", "Generate subtitles"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("elevenlabs", "ElevenLabs"),
                            ("local", "Local"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("progress_current", models.PositiveIntegerField(default=0)),
                ("progress_total", models.PositiveIntegerField(default=0)),
                ("progress_message", models.CharField(blank=True, max_length=255)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "actual_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who authorized this step. The audit trail for spend.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for video-level steps (script, split, render).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="videos.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("elevenlabs", "ElevenLabs"),
                            ("local", "Local"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=200)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "units",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. input_tokens, output_tokens, images, characters.",
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to="videos.generationstep",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "premise",
                    models.TextField(
                        help_text="User-entered premise/topic for the story."
                    ),
                ),
                ("target_minutes", models.PositiveIntegerField(default=90)),
                ("title", models.CharField(blank=True, max_length=300)),
                (
                    "script",
                    models.TextField(
                        blank=True, help_text="Full continuous script text."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("script", "Script generated"),
                            ("split", "Split into parts"),
                            ("images", "Images generated"),
                            ("narration", "Narration generated"),
                            ("rendering", "Rendering"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_words", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("narration_audio_path", models.CharField(blank=True, max_length=500)),
                ("final_video_path", models.CharField(blank=True, max_length=500)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="templates.template",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="generationstep",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="videos.video",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="videos.video",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("video", "chapter_number")},
        ),
    ]
