# Generated by Django 5.2.16 on 2026-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationstep",
            name="progress_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generationstep",
            name="progress_message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="generationstep",
            name="progress_total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
