# Generated by Django 5.2.16 on 2026-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="subtitles_path",
            field=models.CharField(
                blank=True,
                help_text="SRT under media/, produced by the optional subtitles step.",
                max_length=500,
            ),
        ),
    ]
