# Generated by Django 5.2.16 on 2026-07-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_generationstep_progress_current_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("script", "Generate script"),
                    ("split", "Split into parts"),
                    ("images", "Generate images"),
                    ("narration", "Generate narration"),
                    ("merge", "Merge narration"),
                    ("render", "Render video"),
                    ("subtitles", "Generate subtitles"),
                ],
                max_length=20,
            ),
        ),
    ]
