# Generated by Django 5.2.16 on 2026-07-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_generationstep_step_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="video_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="generationstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("script", "Generate script"),
                    ("split", "Split into parts"),
                    ("images", "Generate images"),
                    ("narration", "Generate narration"),
                    ("render_part", "Render part video"),
                    ("merge", "Merge narration"),
                    ("render", "Render video"),
                    ("subtitles", "Generate subtitles"),
                ],
                max_length=20,
            ),
        ),
    ]
